-- xjh.bill_list definition

CREATE TABLE `bill_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderNums` int(8) NOT NULL,
  `customerNums` int(8) NOT NULL,
  `h5OrderNums` int(8) NOT NULL,
  `totalDishesPrice` double(11,2) NOT NULL,
  `totalErasePrice` double(11,2) NOT NULL,
  `totalDiscountPrice` double(11,2) NOT NULL,
  `totalReturnPrice` double(11,2) NOT NULL,
  `totalHadPaidPrice` double(11,2) NOT NULL,
  `totalRefundPrice` double(11,2) NOT NULL,
  `totalFreePrice` double(11,2) NOT NULL,
  `totalFreeNums` int(8) NOT NULL,
  `totalEscapePrice` double(11,2) NOT NULL,
  `totalEscapeNums` int(8) NOT NULL,
  `totalUnpaidPrice` double(11,2) NOT NULL,
  `totalUnpaidNums` int(8) NOT NULL,
  `methodCashTotal` double(11,2) NOT NULL,
  `methodCashTotalNums` int(8) NOT NULL,
  `methodBankcardTotal` double(11,2) NOT NULL,
  `methodBankcardTotalNums` int(8) NOT NULL,
  `methodWechatTotal` double(11,2) NOT NULL,
  `methodWechatTotalNums` int(8) NOT NULL,
  `methodAlipayTotal` double(11,2) NOT NULL,
  `methodAlipayTotalNums` int(8) NOT NULL,
  `methodStoreCardTotal` double(11,2) NOT NULL,
  `methodStoreCardTotalNums` int(8) NOT NULL,
  `methodMeituanTotal` double(11,2) NOT NULL,
  `methodMeituanTotalNums` int(8) NOT NULL,
  `methodCouponTotal` double(11,2) NOT NULL,
  `methodCouponTotalNums` int(8) NOT NULL,
  `methodKouBeiTotal` double(11,2) NOT NULL,
  `methodKouBeiTotalNums` int(8) NOT NULL,
  `methodPublicSignalTotal` double(11,2) NOT NULL,
  `methodPublicSignalTotalNums` int(8) NOT NULL,
  `methodWechatCouponTotal` double(11,2) NOT NULL,
  `actualWechatCouponTotal` double(11,2) NOT NULL,
  `methodWechatCouponTotalNums` int(8) NOT NULL,
  `actualMeituanTotal` double(11,2) NOT NULL,
  `actualKouBeiTotal` double(11,2) NOT NULL,
  `actualPublicSignalTotal` double(11,2) NOT NULL,
  `totalReductionPrice` double(11,2) NOT NULL,
  `methodPackageTotal` double(11,2) NOT NULL,
  `methodPackageTotalNums` int(8) NOT NULL,
  `methodStoreReduceTotal` double(11,2) NOT NULL,
  `methodStoreReduceTotalNums` int(8) NOT NULL,
  `dateTime` bigint(13) NOT NULL,
  `totalReturnCashPrice` double(11,2) NOT NULL,
  `actualPackageTotal` double(11,2) NOT NULL,
  `methodOtherTotal` double(11,2) NOT NULL,
  `actualOtherTotal` double(11,2) NOT NULL,
  `methodOtherTotalNums` int(8) NOT NULL,
  `methodWandaTotal` double(11,2) NOT NULL,
  `actualWandaTotal` double(11,2) NOT NULL,
  `methodWandaTotalNums` int(8) NOT NULL,
  `methodWandaPackageTotal` double(11,2) NOT NULL,
  `actualWandaPackageTotal` double(11,2) NOT NULL,
  `methodWandaPackageTotalNums` int(8) NOT NULL,
  `methodSelfHelpPriceTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `actualStoreCardTotal` double(11,2) NOT NULL,
  `methodTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeCouponTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotalNums` int(8) NOT NULL DEFAULT '0',
  `methodTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖总金额',
  `methodTakeOutTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '外卖总数量',
  `actualTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖实际金额',
  `methodUnionpayPosTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '银联pos总金额',
  `methodUnionpayPosTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '银联pos总数量',
  `methodTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动总金额',
  `methodTrafficActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '交行活动总数量',
  `actualTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动实际金额',
  `methodMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动总金额',
  `methodMerchantsActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '招行活动总数量',
  `actualMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动实际金额',
  `methodMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动总金额',
  `methodMarketActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '商场活动总数量',
  `actualMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动实际金额',
  `methodMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠总金额',
  `methodMeituanShanhuiTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '美团闪惠总数量',
  `actualMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠实际金额',
  PRIMARY KEY (`id`),
  KEY `dateTime` (`dateTime`)
) ENGINE=MyISAM AUTO_INCREMENT=2327 DEFAULT CHARSET=utf8;


CREATE TABLE `bill_list_night` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderNums` int(8) NOT NULL,
  `customerNums` int(8) NOT NULL,
  `h5OrderNums` int(8) NOT NULL,
  `totalDishesPrice` double(11,2) NOT NULL,
  `totalErasePrice` double(11,2) NOT NULL,
  `totalDiscountPrice` double(11,2) NOT NULL,
  `totalReturnPrice` double(11,2) NOT NULL,
  `totalHadPaidPrice` double(11,2) NOT NULL,
  `totalRefundPrice` double(11,2) NOT NULL,
  `totalFreePrice` double(11,2) NOT NULL,
  `totalFreeNums` int(8) NOT NULL,
  `totalEscapePrice` double(11,2) NOT NULL,
  `totalEscapeNums` int(8) NOT NULL,
  `totalUnpaidPrice` double(11,2) NOT NULL,
  `totalUnpaidNums` int(8) NOT NULL,
  `methodCashTotal` double(11,2) NOT NULL,
  `methodCashTotalNums` int(8) NOT NULL,
  `methodBankcardTotal` double(11,2) NOT NULL,
  `methodBankcardTotalNums` int(8) NOT NULL,
  `methodWechatTotal` double(11,2) NOT NULL,
  `methodWechatTotalNums` int(8) NOT NULL,
  `methodAlipayTotal` double(11,2) NOT NULL,
  `methodAlipayTotalNums` int(8) NOT NULL,
  `methodStoreCardTotal` double(11,2) NOT NULL,
  `methodStoreCardTotalNums` int(8) NOT NULL,
  `methodMeituanTotal` double(11,2) NOT NULL,
  `methodMeituanTotalNums` int(8) NOT NULL,
  `methodCouponTotal` double(11,2) NOT NULL,
  `methodCouponTotalNums` int(8) NOT NULL,
  `methodKouBeiTotal` double(11,2) NOT NULL,
  `methodKouBeiTotalNums` int(8) NOT NULL,
  `methodPublicSignalTotal` double(11,2) NOT NULL,
  `methodPublicSignalTotalNums` int(8) NOT NULL,
  `methodWechatCouponTotal` double(11,2) NOT NULL,
  `actualWechatCouponTotal` double(11,2) NOT NULL,
  `methodWechatCouponTotalNums` int(8) NOT NULL,
  `actualMeituanTotal` double(11,2) NOT NULL,
  `actualKouBeiTotal` double(11,2) NOT NULL,
  `actualPublicSignalTotal` double(11,2) NOT NULL,
  `totalReductionPrice` double(11,2) NOT NULL,
  `methodPackageTotal` double(11,2) NOT NULL,
  `methodPackageTotalNums` int(8) NOT NULL,
  `methodStoreReduceTotal` double(11,2) NOT NULL,
  `methodStoreReduceTotalNums` int(8) NOT NULL,
  `dateTime` bigint(13) NOT NULL,
  `totalReturnCashPrice` double(11,2) NOT NULL,
  `actualPackageTotal` double(11,2) NOT NULL,
  `methodOtherTotal` double(11,2) NOT NULL,
  `actualOtherTotal` double(11,2) NOT NULL,
  `methodOtherTotalNums` int(8) NOT NULL,
  `methodWandaTotal` double(11,2) NOT NULL,
  `actualWandaTotal` double(11,2) NOT NULL,
  `methodWandaTotalNums` int(8) NOT NULL,
  `methodWandaPackageTotal` double(11,2) NOT NULL,
  `actualWandaPackageTotal` double(11,2) NOT NULL,
  `methodWandaPackageTotalNums` int(8) NOT NULL,
  `methodSelfHelpPriceTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `actualStoreCardTotal` double(11,2) NOT NULL,
  `methodTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeCouponTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotalNums` int(8) NOT NULL DEFAULT '0',
  `methodTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖总金额',
  `methodTakeOutTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '外卖总数量',
  `actualTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖实际金额',
  `methodUnionpayPosTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '银联pos总金额',
  `methodUnionpayPosTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '银联pos总数量',
  `methodTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动总金额',
  `methodTrafficActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '交行活动总数量',
  `actualTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动实际金额',
  `methodMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动总金额',
  `methodMerchantsActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '招行活动总数量',
  `actualMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动实际金额',
  `methodMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动总金额',
  `methodMarketActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '商场活动总数量',
  `actualMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动实际金额',
  `methodMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠总金额',
  `methodMeituanShanhuiTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '美团闪惠总数量',
  `actualMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠实际金额',
  PRIMARY KEY (`id`),
  KEY `dateTime` (`dateTime`)
) ENGINE=MyISAM AUTO_INCREMENT=2159 DEFAULT CHARSET=utf8;

CREATE TABLE `bill_list_noon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderNums` int(8) NOT NULL,
  `customerNums` int(8) NOT NULL,
  `h5OrderNums` int(8) NOT NULL,
  `totalDishesPrice` double(11,2) NOT NULL,
  `totalErasePrice` double(11,2) NOT NULL,
  `totalDiscountPrice` double(11,2) NOT NULL,
  `totalReturnPrice` double(11,2) NOT NULL,
  `totalHadPaidPrice` double(11,2) NOT NULL,
  `totalRefundPrice` double(11,2) NOT NULL,
  `totalFreePrice` double(11,2) NOT NULL,
  `totalFreeNums` int(8) NOT NULL,
  `totalEscapePrice` double(11,2) NOT NULL,
  `totalEscapeNums` int(8) NOT NULL,
  `totalUnpaidPrice` double(11,2) NOT NULL,
  `totalUnpaidNums` int(8) NOT NULL,
  `methodCashTotal` double(11,2) NOT NULL,
  `methodCashTotalNums` int(8) NOT NULL,
  `methodBankcardTotal` double(11,2) NOT NULL,
  `methodBankcardTotalNums` int(8) NOT NULL,
  `methodWechatTotal` double(11,2) NOT NULL,
  `methodWechatTotalNums` int(8) NOT NULL,
  `methodAlipayTotal` double(11,2) NOT NULL,
  `methodAlipayTotalNums` int(8) NOT NULL,
  `methodStoreCardTotal` double(11,2) NOT NULL,
  `methodStoreCardTotalNums` int(8) NOT NULL,
  `methodMeituanTotal` double(11,2) NOT NULL,
  `methodMeituanTotalNums` int(8) NOT NULL,
  `methodCouponTotal` double(11,2) NOT NULL,
  `methodCouponTotalNums` int(8) NOT NULL,
  `methodKouBeiTotal` double(11,2) NOT NULL,
  `methodKouBeiTotalNums` int(8) NOT NULL,
  `methodPublicSignalTotal` double(11,2) NOT NULL,
  `methodPublicSignalTotalNums` int(8) NOT NULL,
  `methodWechatCouponTotal` double(11,2) NOT NULL,
  `actualWechatCouponTotal` double(11,2) NOT NULL,
  `methodWechatCouponTotalNums` int(8) NOT NULL,
  `actualMeituanTotal` double(11,2) NOT NULL,
  `actualKouBeiTotal` double(11,2) NOT NULL,
  `actualPublicSignalTotal` double(11,2) NOT NULL,
  `totalReductionPrice` double(11,2) NOT NULL,
  `methodPackageTotal` double(11,2) NOT NULL,
  `methodPackageTotalNums` int(8) NOT NULL,
  `methodStoreReduceTotal` double(11,2) NOT NULL,
  `methodStoreReduceTotalNums` int(8) NOT NULL,
  `dateTime` bigint(13) NOT NULL,
  `totalReturnCashPrice` double(11,2) NOT NULL,
  `actualPackageTotal` double(11,2) NOT NULL,
  `methodOtherTotal` double(11,2) NOT NULL,
  `actualOtherTotal` double(11,2) NOT NULL,
  `methodOtherTotalNums` int(8) NOT NULL,
  `methodWandaTotal` double(11,2) NOT NULL,
  `actualWandaTotal` double(11,2) NOT NULL,
  `methodWandaTotalNums` int(8) NOT NULL,
  `methodWandaPackageTotal` double(11,2) NOT NULL,
  `actualWandaPackageTotal` double(11,2) NOT NULL,
  `methodWandaPackageTotalNums` int(8) NOT NULL,
  `methodSelfHelpPriceTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `actualStoreCardTotal` double(11,2) NOT NULL,
  `methodTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeCouponTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotalNums` int(8) NOT NULL DEFAULT '0',
  `methodTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖总金额',
  `methodTakeOutTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '外卖总数量',
  `actualTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖实际金额',
  `methodUnionpayPosTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '银联pos总金额',
  `methodUnionpayPosTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '银联pos总数量',
  `methodTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动总金额',
  `methodTrafficActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '交行活动总数量',
  `actualTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动实际金额',
  `methodMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动总金额',
  `methodMerchantsActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '招行活动总数量',
  `actualMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动实际金额',
  `methodMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动总金额',
  `methodMarketActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '商场活动总数量',
  `actualMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动实际金额',
  `methodMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠总金额',
  `methodMeituanShanhuiTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '美团闪惠总数量',
  `actualMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠实际金额',
  PRIMARY KEY (`id`),
  KEY `dateTime` (`dateTime`)
) ENGINE=MyISAM AUTO_INCREMENT=2159 DEFAULT CHARSET=utf8;



CREATE TABLE `bill_list_supper` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderNums` int(8) NOT NULL,
  `customerNums` int(8) NOT NULL,
  `h5OrderNums` int(8) NOT NULL,
  `totalDishesPrice` double(11,2) NOT NULL,
  `totalErasePrice` double(11,2) NOT NULL,
  `totalDiscountPrice` double(11,2) NOT NULL,
  `totalReturnPrice` double(11,2) NOT NULL,
  `totalHadPaidPrice` double(11,2) NOT NULL,
  `totalRefundPrice` double(11,2) NOT NULL,
  `totalFreePrice` double(11,2) NOT NULL,
  `totalFreeNums` int(8) NOT NULL,
  `totalEscapePrice` double(11,2) NOT NULL,
  `totalEscapeNums` int(8) NOT NULL,
  `totalUnpaidPrice` double(11,2) NOT NULL,
  `totalUnpaidNums` int(8) NOT NULL,
  `methodCashTotal` double(11,2) NOT NULL,
  `methodCashTotalNums` int(8) NOT NULL,
  `methodBankcardTotal` double(11,2) NOT NULL,
  `methodBankcardTotalNums` int(8) NOT NULL,
  `methodWechatTotal` double(11,2) NOT NULL,
  `methodWechatTotalNums` int(8) NOT NULL,
  `methodAlipayTotal` double(11,2) NOT NULL,
  `methodAlipayTotalNums` int(8) NOT NULL,
  `methodStoreCardTotal` double(11,2) NOT NULL,
  `methodStoreCardTotalNums` int(8) NOT NULL,
  `methodMeituanTotal` double(11,2) NOT NULL,
  `methodMeituanTotalNums` int(8) NOT NULL,
  `methodCouponTotal` double(11,2) NOT NULL,
  `methodCouponTotalNums` int(8) NOT NULL,
  `methodKouBeiTotal` double(11,2) NOT NULL,
  `methodKouBeiTotalNums` int(8) NOT NULL,
  `methodPublicSignalTotal` double(11,2) NOT NULL,
  `methodPublicSignalTotalNums` int(8) NOT NULL,
  `methodWechatCouponTotal` double(11,2) NOT NULL,
  `actualWechatCouponTotal` double(11,2) NOT NULL,
  `methodWechatCouponTotalNums` int(8) NOT NULL,
  `actualMeituanTotal` double(11,2) NOT NULL,
  `actualKouBeiTotal` double(11,2) NOT NULL,
  `actualPublicSignalTotal` double(11,2) NOT NULL,
  `totalReductionPrice` double(11,2) NOT NULL,
  `methodPackageTotal` double(11,2) NOT NULL,
  `methodPackageTotalNums` int(8) NOT NULL,
  `methodStoreReduceTotal` double(11,2) NOT NULL,
  `methodStoreReduceTotalNums` int(8) NOT NULL,
  `dateTime` bigint(13) NOT NULL,
  `totalReturnCashPrice` double(11,2) NOT NULL,
  `actualPackageTotal` double(11,2) NOT NULL,
  `methodOtherTotal` double(11,2) NOT NULL,
  `actualOtherTotal` double(11,2) NOT NULL,
  `methodOtherTotalNums` int(8) NOT NULL,
  `methodWandaTotal` double(11,2) NOT NULL,
  `actualWandaTotal` double(11,2) NOT NULL,
  `methodWandaTotalNums` int(8) NOT NULL,
  `methodWandaPackageTotal` double(11,2) NOT NULL,
  `actualWandaPackageTotal` double(11,2) NOT NULL,
  `methodWandaPackageTotalNums` int(8) NOT NULL,
  `methodSelfHelpPriceTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `actualStoreCardTotal` double(11,2) NOT NULL,
  `methodTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeCouponTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeCouponTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeIntegralDeductionTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeIntegralDeductionTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodTinyLifeStorecardTotalNums` int(8) NOT NULL DEFAULT '0',
  `actualTinyLifeStorecardTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotal` double(11,2) NOT NULL DEFAULT '0.00',
  `methodWeChatUnionpayPayMentTotalNums` int(8) NOT NULL DEFAULT '0',
  `methodTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖总金额',
  `methodTakeOutTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '外卖总数量',
  `actualTakeOutTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '外卖实际金额',
  `methodUnionpayPosTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '银联pos总金额',
  `methodUnionpayPosTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '银联pos总数量',
  `methodTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动总金额',
  `methodTrafficActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '交行活动总数量',
  `actualTrafficActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '交行活动实际金额',
  `methodMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动总金额',
  `methodMerchantsActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '招行活动总数量',
  `actualMerchantsActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '招行活动实际金额',
  `methodMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动总金额',
  `methodMarketActivitiesTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '商场活动总数量',
  `actualMarketActivitiesTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '商场活动实际金额',
  `methodMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠总金额',
  `methodMeituanShanhuiTotalNums` int(8) NOT NULL DEFAULT '0' COMMENT '美团闪惠总数量',
  `actualMeituanShanhuiTotal` double(11,2) NOT NULL DEFAULT '0.00' COMMENT '美团闪惠实际金额',
  PRIMARY KEY (`id`),
  KEY `dateTime` (`dateTime`)
) ENGINE=MyISAM AUTO_INCREMENT=2159 DEFAULT CHARSET=utf8;





